### ISSUE TITLE
Applications crash

### ISSUE THREAD

**Issue by PPORCH3bis** [flipperdevices/Flipper-Android-App#601]
**Describe the bug**
On my S22 Ultra to apps close itslef when I click on Apps in Hub.
On my watch pro 5, I can't start the app.

**To Reproduce**
On phone
1. Connect to the flipper
2. Go to Hub
3. Click on Apps
4. The app closed itself 

On watch
1. Click on the app
2. I see flipper
3. I see a circle with a white background
4. The app closed itself

**Expected behavior**
I want to see the app menu and use flipper with my watch.

I'm on the last version in playstore.
Hope to say everything.

**Comment by BoBeR182** [comment]
LineageOS 18.1
Flipper 1.5.0 from fdroid
```
Failed load suggested item
java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
	at yp.r.b(Unknown Source:2488)
	at yp.v0.c(Unknown Source:24)
	at yp.u0.invoke(Unknown Source:44)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy2.b(Unknown Source)
	at rb.e.g(Unknown Source:54)
	at um.a.C(Unknown Source:8)
	at rn.m0.run(Unknown Source:107)
	at androidx.appcompat.widget.j.run(Unknown Source:18)
	at xn.i.run(Unknown Source:2)
	at xn.a.run(Unknown Source:93)
Failed load suggested item
java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
	at yp.r.b(Unknown Source:2488)
	at yp.v0.c(Unknown Source:24)
	at yp.u0.invoke(Unknown Source:44)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy2.b(Unknown Source)
	at rb.e.g(Unknown Source:54)
	at um.a.C(Unknown Source:8)
	at rn.m0.run(Unknown Source:107)
	at androidx.appcompat.widget.j.run(Unknown Source:18)
	at xn.i.run(Unknown Source:2)
	at xn.a.run(Unknown Source:93)
FATAL EXCEPTION: main
Process: com.flipperdevices.app, PID: 30280
java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
	at yp.r.b(Unknown Source:2488)
	at yp.v0.c(Unknown Source:24)
	at yp.u0.invoke(Unknown Source:44)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy3.b(Unknown Source)
	at wb.g.b(Unknown Source:71)
	at rb.c.g(Unknown Source:45)
	at um.a.C(Unknown Source:8)
	at rn.m0.run(Unknown Source:107)
	at androidx.appcompat.widget.j.run(Unknown Source:18)
	at xn.i.run(Unknown Source:2)
	at xn.a.run(Unknown Source:93)
	Suppressed: wn.f: [y1{Cancelling}@6b7302f, Dispatchers.Main.immediate]
```
