### ISSUE TITLE
App crashes on Android 14 when Play Store not installed

### ISSUE THREAD

**Issue by no-usernames-left** [flipperdevices/Flipper-Android-App#719]
**Describe the bug**
On Android 14 (GrapheneOS), the previous version of the Flipper app worked perfectly but the latest version is crashing and complaining about the Play Store not being installed (which has never been installed on my device).

**To Reproduce**
1. Hold your Pixel with GrapheneOS (and without Play Store) in your hand
2. Have the latest Flipper Android app installed (for example, via Aurora Store) and already paired to your Flipper back when the app worked
3. Launch it
4. It burns

**Expected behavior**
Flip the World! 😬 

**Logs**
```
type: crash
osVersion: google/redfin/redfin:14/UP1A.231005.007/2023101300:user/release-keys
package: com.flipperdevices.app:1270
process: com.flipperdevices.app
processUptime: 15432 + 353 ms
installer: com.aurora.store

sn.j: -9: Install Error(-9): The Play Store app is either not installed or not the official version. (https://developer.android.com/reference/com/google/android/play/core/install/model/InstallErrorCode#ERROR_PLAY_STORE_NOT_FOUND)
    at gp.l.c(Unknown Source:37)
    at mk.c.<init>(Unknown Source:37)
    at mk.d.get(Unknown Source:26)
    at gq.c.get(Unknown Source:13)
    at nk.c.get(Unknown Source:2)
    at gq.c.get(Unknown Source:13)
    at com.flipperdevices.singleactivity.impl.SingleActivity.onCreate(Unknown Source:696)
    at android.app.Activity.performCreate(Activity.java:8651)
    at android.app.Activity.performCreate(Activity.java:8629)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1461)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3775)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3933)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2450)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8199)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ExecInit.main(ExecInit.java:49)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
    Suppressed: ot.g: [w1{Cancelling}@3dd55cf, Dispatchers.Default]

```

**Comment by nick-perry14** [comment]
Can confirm same logs today.  Although play store IS installed on my device, but not signed in and sandboxed, same issue.  I installed via aurora store as well.

**Comment by LionZXY** [comment]
First of all, it's wrong that you're using the Google Play version on other platforms.
Use the version from F-Droid or directly downloaded from GitHub.

But #720 should fix this behaviour

**Comment by nick-perry14** [comment]
> First of all, it's wrong that you're using the Google Play version on other platforms. Use the version from F-Droid or directly downloaded from GitHub.
> 
> But #720 should fix this behaviour

Have to agree with @no-usernames-left here.  No reason to get nasty about us using the play version.

To be fair, I didn't know there was an F-Droid official version, as it's not advertised

**Comment by LionZXY** [comment]
What happened is definitely a problem. We failed. We made a number of internal decisions to reduce the likelihood of this happening in the future.

We cannot test the F-Droid version "as is" because it is built on the F-Droid side. But we will try to test as close as possible to what is going to be released.

Version 1.6.6 with fix in Google's review
